### ISSUE TITLE
Could you please change how the app starts up? 

### ISSUE THREAD

**Issue by Stehlampe2020** [OpenBoard-org/OpenBoard#600] opened 2022-05-17 04:26 UTC
I don't like it that the app creates a new document on every startup.   
What I would suggest:   
There is a setting where to start to, please add these item(s) to that list:   
* Documents view   
* (Internet view)?   
   
It's nothing too important, I just would like to be able to set OpenBoard so that it doesn't create a new document on every startup.

**Comment by letsfindaway** [comment] 2022-05-17 05:34
For the new document at startup: see also #578. If you do not modify the new document, then it is removed when you exit OpenBoard.

For the startup mode: this is a good idea, independent of your intent to inhibit creation of a new document: There is already a combobox in the preferences where you can select between `Board` and `Desktop` mode. Your idea would just suggest to add `Document` and `Internet` to the list of available choices. Especially `Document` mode seems to be quite useful to me.

**Comment by Stehlampe2020** [comment] 2022-05-17 06:29
> For the startup mode: this is a good idea, independent of your intent to inhibit creation of a new document: There is already a combobox in the preferences where you can select between `Board` and `Desktop` mode. Your idea would just suggest to add `Document` and `Internet` to the list of available choices. Especially `Document` mode seems to be quite useful to me.   

I know of this setting and what I wanted to "say" is: please add these items to there ;)   
(I think I didn't write it clearly and unmisunderstandable in the original post)

**Comment by maehne** [comment] 2022-05-19 11:31
It would be also nice if OpenBoard could be configured to reopen the last opened document.

**Comment by kaamui** [comment] 2022-05-20 10:51
it had been done during the development of 1.5.3 (62a5ad33), but had to be reverted because of issues in osx (42b08ef). It was not a priority so I didn't investigate more but I don't think it would be hard to fix (finder and other things were overlapping the Document Mode if I remember well). I'll try to look at it so it can be fixed for 1.7.0 or 1.7.1.

> It would be also nice if OpenBoard could be configured to reopen the last opened document.

This is a totally different feature, but it would be great indeed^^. A similar improvement is scheduled where documents can be marked as "Favorite" and appear in the "Favorites" folder in the library (the right palette in Board Mode). The initial idea is to be able to swap between two documents quicker, but I guess it would also serve your purpose.

**Comment by Stehlampe2020** [comment] 2022-05-22 09:23
> I'll try to look at it so it can be fixed for 1.7.0 or 1.7.1.   

That would be nice!

**Comment by maehne** [comment] 2022-05-23 17:21
@kaamui: Thanks for the feedback! Marking one or more documents as favourites could indeed be useful to swap between several documents quickly during a teaching session. However, for that case a tabbed interface might be more intuitive. Having an option that makes OpenBoard to always reopen the last opened document would still be useful: It's easy to forget to mark a document as favourite at the end of the lesson. It would also save time when it is needed to restart OpenBoard during a lesson, e.g., in case of a crash of OpenBoard.

Would an automatic favourite "Last document" be an option? Should I file a separate issue for this?

**Comment by Stehlampe2020** [comment] 2022-05-23 19:00
> Would an automatic favourite "Last document" be an option?   

I think yes, but it should be able to be turned off. Otherwise it would get on my nerves pretty quickly, as I am using OpenBoard as a student in several different lessons, so I don't need to reopen the same document on every start. 

@maehne Is there a reason why OpenBoard calls itself "Öppna Sankoré" in Swedish (at least on Linux)? I have read that OpenBoard is a fork of Open Sankoré, but it's weird to see it call itself "Öppna Sankoré".

**Comment by maehne** [comment] 2022-05-23 20:40
@Stehlampe2020: Indeed, also as a lecturer, I am working over the week with several slide decks. So, maybe it would be more flexible to offer a list (of maybe configurable length) of the most recently used documents, to allow easy switching between them. This is quite common in many applications. What would be also helpful where a way to quickly clean all annotations from all slides of a deck, e.g., if you have to teach the same topic in several classes. The existing erase button plus some modifier keys (e.g.: CTRL + ALT or CMD + ALT) could be an option. Ideally, the label of the icon should adjust accordingly to give visual feedback. A confirmation dialogue might be also due, to avoid loosing annotations one might want to keep.

I am not an OpenBoard developer, but I would assume that inconsistencies like the one you found in the Swedish localisation are unwanted. Probably, no one offered a PR to clean this up. Maintaining localisations consistent can be very labourious.

**Comment by kaamui** [comment] 2022-05-24 08:35
> @maehne Is there a reason why OpenBoard calls itself "Öppna Sankoré" in Swedish (at least on Linux)? I have read that OpenBoard is a fork of Open Sankoré, but it's weird to see it call itself "Öppna Sankoré".

Officially supported languages are French, English, Italian and German. All the other languages are maintained by the community. If possible, please provide an update of the Swedish localisation via a pull request (PR) and I'll be glad to add it to the next version

**Comment by maehne** [comment] 2022-05-30 16:40
> I don't think this will ever be a priority for our teachers at Geneva. They are constantly changing of classroom and never expressed the need of opening the last document in their next session

@kaamui: I can understand this reasoning. I just experienced on several occasions that OpenBoard suddenly crashed during my presentations in the classrooms. Restarting OpenBoard, loading the last document and advancing to the last slide manually caused unnecessary delays, I would have liked to avoid.

As a lecturer, I have to switch between different classes / topics frequently during my work week. Not always, I can finish a slide set on one topic after one session. In these cases, it would be nice if there would be a way to pick up from the last slide, which I showed the week before. Currently, this information does not seem to get stored in OpenBoard, as it seems to always open slide sets in the document view from slide 1.

**Comment by Stehlampe2020** [comment] 2022-05-30 17:38
> I just experienced on several occasions that OpenBoard suddenly crashed during my presentations in the classrooms.   

I have seen that OpenBoard crashes everytimes when I try to play a video in the "Internet" section (for example YouTube, HTML5 <video> tag).

**Comment by letsfindaway** [comment] 2022-05-31 05:35
> > I just experienced on several occasions that OpenBoard suddenly crashed during my presentations in the classrooms.
> 
> I have seen that OpenBoard crashes everytimes when I try to play a video in the "Internet" section (for example YouTube, HTML5

A crash of OpenBoard is a completely different issue than the original question of this topic. It would help if you create separate issues for separate topics. And when reporting a crash please be as specific as possible: what are the circumstances? Can you give a step-by-step instruction to reproduce it? It it crashes on a URL, can you report the URL? This would help in investigating the topic.

**Closed** 2022-05-31 15:04 UTC

**Comment by GavinSmith0123** [comment] 2025-02-20 20:08
I changed [my fork of OpenBoard](https://github.com/GavinSmith0123/OpenBoard/commits/smart-import-build/) (which I use for my personal use) to start up in "Documents" view rather than board view, and to avoid creating a new blank document whenever I open the program, as this cluttered the list of documents. Some existing document is opened instead (I don't mind which one):

````
commit 422e482c6bfe425f19d7abac7073076bb3f5a9c8
Author: Gavin Smith <gavinsmith0123@gmail.com>
Date:   2025-02-20 17:24:42 +0000

    start in document view and do not create new document

diff --git a/src/board/UBBoardController.cpp b/src/board/UBBoardController.cpp
index dd5afac5..889a4310 100644
--- a/src/board/UBBoardController.cpp
+++ b/src/board/UBBoardController.cpp
@@ -147,7 +147,11 @@ void UBBoardController::init()
     connect(UBDownloadManager::downloadManager(), SIGNAL(downloadModalFinished()), this, SLOT(onDownloadModalFinished()));
     connect(UBDownloadManager::downloadManager(), SIGNAL(addDownloadedFileToBoard(bool,QUrl,QUrl,QString,QByteArray,QPointF,QSize,bool)), this, SLOT(downloadFinished(bool,QUrl,QUrl,QString,QByteArray,QPointF,QSize,bool)));
 
-    UBDocumentProxy* doc = UBPersistenceManager::persistenceManager()->createNewDocument();
+    /* load an existing document if one exists, else create a new document. */
+    UBDocumentProxy* doc;
+    doc = UBPersistenceManager::persistenceManager()->findDefaultDocument();
+    if (!doc)
+      doc = UBPersistenceManager::persistenceManager()->createNewDocument();
 
     setActiveDocumentScene(doc);
 
diff --git a/src/core/UBApplication.cpp b/src/core/UBApplication.cpp
index beb6bd70..f9de3c93 100644
--- a/src/core/UBApplication.cpp
+++ b/src/core/UBApplication.cpp
@@ -374,7 +374,9 @@ int UBApplication::exec(const QString& pFileToImport)
     if (UBSettings::settings()->appStartMode->get().toInt())
         applicationController->showDesktop();
     else
-        applicationController->showBoard();
+        //applicationController->showBoard();
+        // start in document list
+        applicationController->showDocument();
 
     emit UBDrawingController::drawingController()->colorPaletteChanged();
 
diff --git a/src/core/UBPersistenceManager.cpp b/src/core/UBPersistenceManager.cpp
index 7b5d033c..58f99e2d 100644
--- a/src/core/UBPersistenceManager.cpp
+++ b/src/core/UBPersistenceManager.cpp
@@ -530,6 +530,25 @@ UBDocumentProxy* UBPersistenceManager::createNewDocument(const QString& pGroupNa
     return resultDoc;
 }
 
+UBDocumentProxy* UBPersistenceManager::findDefaultDocument(const QModelIndex &parentIndex)
+{
+    for (int i = 0; i < mDocumentTreeStructureModel->rowCount(parentIndex); i++)
+    {
+        QModelIndex currentIndex = mDocumentTreeStructureModel->index(i, 0, parentIndex);
+        if (!mDocumentTreeStructureModel->isCatalog(currentIndex))
+        {
+            return mDocumentTreeStructureModel->proxyData(currentIndex);
+        }
+        else
+        {
+            UBDocumentProxy *result = findDefaultDocument(currentIndex);
+            if (result)
+              return result;
+        }
+    }
+    return NULL;
+}
+
 UBDocumentProxy* UBPersistenceManager::createDocumentFromDir(const QString& pDocumentDirectory
                                                              , const QString& pGroupName
                                                              , const QString& pName
diff --git a/src/core/UBPersistenceManager.h b/src/core/UBPersistenceManager.h
index 1a82670e..a3d0fb09 100644
--- a/src/core/UBPersistenceManager.h
+++ b/src/core/UBPersistenceManager.h
@@ -84,6 +84,8 @@ class UBPersistenceManager : public QObject
                 , int pageCount = 0
                 , bool promptDialogIfExists = false);
 
+        virtual UBDocumentProxy *findDefaultDocument(const QModelIndex &pParent = QModelIndex());
+
         virtual UBDocumentProxy* createDocumentFromDir(const QString& pDocumentDirectory
                                                        , const QString& pGroupName = ""
                 , const QString& pName = ""
````

This fork is based against a version of OpenBoard that is a few years' old as I don't have time to keep up with OpenBoard development, so this patch may not apply against the recent development version.

I also made a change to focus the document tree widget, so that I can use the arrow keys on the keyboard immediately to select the document I want to use. It may seem like a small convenience, but every second counts when you are about to present to an audience:

````
commit 4ec8c636a048eddf8fa252aa0f45422e2d1cd01d
Author: Gavin Smith <gavinsmith0123@gmail.com>
Date:   2025-02-20 17:45:49 +0000

    focus document tree view by default

diff --git a/src/document/UBDocumentController.cpp b/src/document/UBDocumentController.cpp
index d3a65669..956cd4d6 100644
--- a/src/document/UBDocumentController.cpp
+++ b/src/document/UBDocumentController.cpp
@@ -2325,6 +2325,7 @@ void UBDocumentController::show()
 
     if(!mToolsPalette)
         setupPalettes();
+    mDocumentUI->documentTreeView->setFocus();
 }
 
 
````

**Comment by letsfindaway** [comment] 2025-02-20 21:05
> I changed [my fork of OpenBoard](https://github.com/GavinSmith0123/OpenBoard/commits/smart-import-build/) (which I use for my personal use) to start up in "Documents" view rather than board view, and to avoid creating a new blank document whenever I open the program, as this cluttered the list of documents. Some existing document is opened instead (I don't mind which one):

Hmm, you can already set the startup mode in the Preferences dialog. And yes, there is a new document created when you start OpenBoard. But when you do not change anything in that document it is deleted when you close the application. So it does not clutter your documents folder.

As far as I can see and as you also stated, you patch is not for the current master, but for some much older version, where setting Document mode for startup was not possible. But this has changed.

**Comment by GavinSmith0123** [comment] 2025-02-20 21:25
OK, that's good to hear it possible to enter Document mode by default. Perhaps the default keyboard focus is worth considering as well?

I disagree that the blank document doesn't clutter the documents, as you can see from the screenshot.

![Image](https://github.com/user-attachments/assets/0a7ad1fc-6d5d-4e30-a225-38ea03cf1a29)
