### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by Merlinux24** [OpenBoard-org/OpenBoard#948] opened 2024-05-05 07:35 UTC
### Describe the bug
<!---

The last file ubx - 9613 KB  -  cannot be imported.  Seemingly it does not let be extracted.

The file ist saved upon NAS of my private network.

This happens, when I save from a computer and attempt to import to another one. Strangely I coul import only after having changed the file name.

But this time it does not workt even when I use the same computer, thus I exported the file to NAS und no loinger cannot imported it. The change of the file name doesn't help too.

What should I do to get it please?

 
   - Linux : ` `Ubuntu
    - Windows : ` ` 10 & 11

**Comment by Merlinux24** [comment] 2024-05-05 07:42
The last file ubx - 9613 KB  -  cannot be imported.  Seemingly it does not let be extracted.

The file ist saved upon NAS of my private network.

This happens, when I save from a computer and attempt to import to another one. Strangely I coul import only after having changed the file name.

But this time it does not workt even when I use the same computer, thus I exported the file to NAS und no loinger cannot imported it. The change of the file name doesn't help too.

What should I do to get it please?

**Comment by Merlinux24** [comment] 2024-05-05 10:25
I just find out that the import only work when I exported to an existing ubx file before, thus not to a new one.

That is really stupid. 

So I am forced to make at first a backup with the window explorer instead of exporting at a glance into a new file...

Likely the bug had with the greater size of the file to do  as I was able to correctly export into a new file at the beginning after having installed OpenBoard. There files were still short indeed.

Please fix this trouble.

Please fix it.

**Comment by letsfindaway** [comment] 2024-05-07 15:07
I pretty much assume that these problems are caused by the interoperation of OpenBoard with your NAS setup. It seems that files are not completely written to the server in some circumstances. It is difficult to tell who is buffering the data: the OS? The NAS client software? Elsewhere? But for sure OpenBoard is writing the file completely and closing it in the end, so I don't think that OpenBoard can do much about it.

I assume that the export works for you if you export to a local drive.

I'm not a NAS expert, but perhaps it helps understanding your problem if you post details about the setup: You operating system, the protocol used to communicate with the NAS, type of NAS, any special client software to talk to the NAS etc.

**Comment by Merlinux24** [comment] 2024-05-07 15:33
I fancy that you're likely right. 

I see myself how OpenBoard completely write to the destination for it takes a long time. By the way the amount of bytes. i.e. the size of the file, is seeable.

However it is unable to load up, it agin, for it takes only a very short time of less than one second  and nothing happens.  I have even not the time to see what the pop-up seemingly for the error message wants to display...

My NAS Server has only 2 SSD Discs on the Raid 1 mode and is connected to the USB port of my German router (Fritzbox 7530 AX). So there are no seetings needed.

I do not want to save on the local drive since I boot from different devices with which I work at any time.

But at least it works when i export two times at glance, That is funny and strange indeed, may be because of Raid 1. It could be,possible  that it is exported to the one disc and cannot be imported from the second one, on which it had not be exported, seemingly until the seconde time I operate... ?????

AK

**Comment by Merlinux24** [comment] 2024-05-15 08:07
I finally have found out that pictures of the library are merely locally saved in the default picture folder of windows in the folder openboard. That is why added pictures in the library  cannot be managed with the export & import function of openboard.

Thus I am forced to manually copy them to the Nas server and from there to paste them locally on every computer...

**Comment by letsfindaway** [comment] 2024-05-15 09:42
That's not fully true. It is correct that pictures of the library are stored in the default picture folder. However when you add an image to a document, it is copied to a subfolder of the document folder. And that document folder is packed into a ZIP archive (and named with the suffix `.ubz`) during export.

When you import a document, this ZIP archive is unpacked. Images on a page are referencing the image file in the document folder, and not in the library. 

- Images in the library are stored in the default picture folder.
- Images in a document are stored in the document folder.
- Export and import only work on the document folder.

**Comment by Merlinux24** [comment] 2024-05-15 17:36
I only meant of course pictures within the library which cannot be exported and imported like the documents.

However I do not see any pictures from documents within a document folder.

But export and import work on any folder which I can choose with the windows explorer., in my case to Nas within my network.

Besides, I did not find out until now where documents with their pictures are "locally" stored, i.e. without using export and import...

**Comment by letsfindaway** [comment] 2024-05-31 09:19
> 
> Besides, I did not find out until now where documents with their pictures are "locally" stored, i.e. without using export and import...

All documents are in a folder called `document` below the folder mentioned in the [Wiki for user configuration](https://github.com/OpenBoard-org/OpenBoard/wiki/Configuration) depending on your OS.

**Closed** 2024-09-27 12:40 UTC
Labels: bug
