### ISSUE TITLE
Mirrored desktop gets distorted if aspect ratio of primary and secondary screen don't match

### ISSUE THREAD

**Issue by maehne** [OpenBoard-org/OpenBoard#618] opened 2022-06-03 12:50 UTC
If one mirrors the screen using the eye tool in the Show Desktop mode, the resulting display of the mirrored screen gets considerably distorted and offset from the expected position if the aspect ratios of the primary and secondary screen don't match.

For the following example, primary screen has resolution of 3440 x 1440 pixels and secondary screen of 1920 x 1200 pixels:

![grafik](https://user-images.githubusercontent.com/1174243/171856369-2cfd3966-f3e6-46fb-970e-36113432ca65.png)

For the following example, primary screen has resolution of 1920 x 1200 pixels and secondary screen of 3440 x 1440 pixels:

![grafik](https://user-images.githubusercontent.com/1174243/171856582-c96a63e8-def0-453e-bb13-fff3624e6e74.png)

Ideally, the output of the mirrored screen should get centered and scaled to fit on the secondary screen without cutting away parts of the desktop.

**Comment by letsfindaway** [comment] 2022-06-03 14:18
See also my PR #569 which should address this issue, which is however not contained in 1.6.2.

**Comment by maehne** [comment] 2022-06-03 14:49
@letsfindaway: Nice to know that there's already a potential fix ready for the next OpenBoard version. I am willing to help with testing, but don't have currently the bandwidth to build binaries from source myself.

**Comment by letsfindaway** [comment] 2022-06-03 15:13
I'm building binary experimental packages for several Linux distributions at https://build.opensuse.org/package/show/home:letsfindaway:experimental/OpenBoard. By clicking on the distribution and version to the right you get to a page where you can download the built rpm or deb packages.

Currently this is an about 2 month old version of 1.7-dev with some patches. I plan to update that to the current 1.7-dev in the next few days (as I find time).

Testers are always welcome! The 1.7-dev branch has some more big changes in the background, especially the new `QWebEngine` based browser, but also the screen configuration is currently reworked (still not in the current builds linked above, but in the upcoming version).

**Comment by maehne** [comment] 2022-06-07 16:36
@letsfindaway: Thanks for the pointer to these test builds. I will have a look. Would be nice if new test builds would get announced in some place.

**Comment by maehne** [comment] 2022-06-10 06:47
@letsfindaway: I tried to download the DEB package for Debian 11 through the above-proved [link](https://build.opensuse.org/package/show/home:letsfindaway:experimental/OpenBoard). However, for download, the web site requires me to create an account for openSUSE Build Service. Is this intented?

**Comment by maehne** [comment] 2022-06-10 08:42
So, I built 1.7-dev (commit 47a96e1d) including your patch from PR #569 on Debian 11. It fixes this issue.

**Comment by letsfindaway** [comment] 2022-06-13 15:10
> @letsfindaway: I tried to download the DEB package for Debian 11 through the above-proved [link](https://build.opensuse.org/package/show/home:letsfindaway:experimental/OpenBoard). However, for download, the web site requires me to create an account for openSUSE Build Service. Is this intented?

Ahh, I see. Yes it is, but there is also a small detour around it, because basically all downloads are open:

- From the link select Debian_11 at the right and click on it.
- From the next page, click on  Go to download repository  directly below the title of the page.
- Then you're at the download server. Select the directory `amd64` and you will find the package.

But building from sources on your own is even better, as I still did not update that build...

**Comment by maehne** [comment] 2022-06-13 16:08
@letsfindaway: Thanks for describing how to download the DEB built by openSUSE Build Service. It works for me. I will temporarilly loose the capability to build OpenBoard in the coming days, as I have to move the Linux distribution to a new laptop. Also, wrapping up the spring term with the coming exam period will absorb a lot of my time due to the necessary grading of exams/projects.

**Comment by letsfindaway** [comment] 2022-06-17 11:06
> @letsfindaway: Thanks for the pointer to these test builds. I will have a look. Would be nice if new test builds would get announced in some place.

A new experimental build is available right now. I now announce them at the following pinned issue in my repository:

[Experimental builds of 1.7](https://github.com/letsfindaway/OpenBoard/issues/89)

**Comment by letsfindaway** [comment] 2023-01-06 17:34
Sorry, but this issue is still there. To make it obvious I rotated my secondary screen, so that it has a very different resolution than the main screen. The result is as follows:

![grafik](https://user-images.githubusercontent.com/35591413/211066031-882e90f0-aa35-4f34-bf2b-018fba91a9b9.png)

Please have another look at my PR #569

**Comment by maehne** [comment] 2023-01-07 09:47
I can confirm this undesirable behaviour. Unfortunately, different aspect ratios are common:

- In the classroom: Convertible laptops have nowadays commonly 16:10, 3:2, or 16:9 ratios and for video projectors 16:9 ratio is most common and less 16:10.

- At the desk: Laptops get connected commonly to desktop monitors with 16:9, 16:10, 32:9, 32:10, etc. ratios.

In both use cases this issue is very inconvenient.

**Comment by kaamui** [comment] 2023-01-10 08:35
> Sorry, but this issue is still there

I know. I closed the issue because the discussion continues on the PR thread and I would like to avoid having two threads for the same discussion. I can reopen it if you want,

**Comment by letsfindaway** [comment] 2023-01-10 08:44
I know, it is grey theory, but ideally the discussion on the issue should be about the problem and the discussion of the PR should be about the solution. Also ideally a issue is closed when the PR is merged, or when the issue is solved in another way.

**Comment by maehne** [comment] 2023-12-09 20:18
The issue persists in version 1.7.0 on all three supported platforms (Linux (Wayland, X11), macOS, Windows).

**Closed** 2024-08-22 09:38 UTC
Labels: bug
