### ISSUE TITLE
Openboard is losing images

### ISSUE THREAD

**Issue by edmondns** [OpenBoard-org/OpenBoard#59] opened 2016-09-10 12:28 UTC
I prepare my course by using the screenshot tool, sometimes as i pass to the next page and want to go back to verify something, I don't find the pasted image.
furthermore it appears in the thumbnail but when i open the page it's not there.
Is there a way to fix this?
I love openboard, but I'm afraid to move all my course there to find them disappear.
I'm using it on a windows 10 64 bit surface pro 3 machine

**Comment by edmondns** [comment] 2016-10-04 15:30
is there anyone else experiencing this issue?
it's quite odd as it doesn't happen for all the images, I really like openboard so for the time being I'm exporting my files before quitting but even with this method, I find lost images as soon as I leave the page containing them.

**Comment by freeheel3r** [comment] 2016-10-04 19:31
Hi,

I've never observed this and I haven't had time to try to replicate the issue on my end, so I can't tell for sure. Does it happen consistently with certain specific images? Or will one image work some times but not others?

Also, do you exit (or switch pages) immediately after adding the image, or do you do anything else on the page (such as adding text, drawing,...)?

**Comment by edmondns** [comment] 2016-10-04 20:07
It's copied and pasted items, screencrops taken by the built in cropping tool or via the onenote cropping tool, either way it's happening but randomly and not with every photo. 
Sometimes I detect it happened when I 'm in class using the lesson I already prepared home and I am surprised to see it's gone, othertimes I change the sheet and I' m happy to see all the photos on the thumbnails but as I access the page, some of them are gone. I will try to take screenshots of the issue. Thank you for your reply 
Le 4 oct. 2016 21:31, Craig <notifications@github.com> a écrit :Hi,

I've never observed this and I haven't had time to try to replicate the issue on my end, so I can't tell for sure. Does it happen consistently with certain specific images? Or will one image work some times but not others?

Also, do you exit (or switch pages) immediately after adding the image, or do you do anything else on the page (such as adding text, drawing,...)?

**Comment by celfred** [comment] 2017-03-15 09:16
I have the same issue : OpenBoard 1.3.5 / Ubuntu 14.04.
In class, I used the system clipboard to copy/paste an image on a page. During the day, I could change document and come back : no problem.
Next day at home. I open the document : the image has disappeared ! (Same behavior with a mp3 file on the same page, also added from a copy/paste).
I don't know if this has an importance : my documents are not stored in the default folder. I've changed my path to /home/celfred/ folder.
I took the time to do a few more tests : 
- copy/paste (the same image) on a new doc, write something on the same page, close/reopen the app > no problem, the image is here.
- copy/paste (the same image) on a new doc, close/reopen the app > no problem, the image is here.
- copy/paste (the same image) on a new doc, copy/paste the same mp3 file I mentioned above), close/reopen the app > no problem, the image is here, the mp3 plays well ...  

Conclusion : I have NO idea what's going on ;) but that's annoying... Maybe a date issue ? I have a feeling tomorrow it might not be working when I'll be back to school. I'm not going to touch anything in the 3 documents mentioned above and I'll keep you updated tomorrow to see if they still work.

**Comment by celfred** [comment] 2017-03-15 09:27
Sorry for coming back so quickly, but I have tried something else with the documents I created in my previous comment : I have dragged/dropped he page with the image in another doc (docB). I went to docB : no problem. I closed/reopen OpenBoard, went back to docB : NO MORE IMAGE (and no more mp3 file).

**Comment by celfred** [comment] 2017-03-15 10:30
The more I think about it, the more I think this is due to copy/paste and drag'n'drop pages in Documents mode.
Here's my usual workflow : preparing docs in classes folders and then drag'n'dropping the pages on a 'Today' document. This way, I keep my originals 'untouched' and what I do in class happens in the 'Today' file which I then drag in an 'archive' folder if needed. So I make use of drag'n' drop A LOT (it's a really cool feature).
And here I notice that EVERY TIME I use this feature, I lose the media files (images/mp3/videos) on the target doc. This is annoying. Especially because you don't lose it right away. It's gone after you close/reopen OpenBoard. The same behavior happens when you hit CTRL+C / CTRL+V on media files.

A simple way to reproduce (at least, on my side, it 'bugs' every time) : Put an image on a page from the library. Close/reopen: No problem. Copy/Paste the image on the same page. Close/Reopen : the copied image is gone. (even the 'Duplicate' icon on top of the image makes a vanishing duplicate).

[Sidenote : I hope I'm not bothering you too much with my 'long' comments.]

**Comment by celfred** [comment] 2017-03-15 10:42
Still investigating...
On a blank new document (the one automatically created at startup) : I put an image from the library, duplicate it, copy/paste it, and then close/reopen OB : no problem !
I do the same steps except I close/reopen RIGHT AFTER my first duplicate and then I do OTHER duplicates and close/reopen again. This time the duplicates are gone.

**Comment by edmondns** [comment] 2017-03-15 12:59
Hi again, in order to not have the problem, we should not use the native copy cut paste but only use openboard's own copy paste tool. 
Since using exclusively this tool, no more disappearing images and openboard becomes reliable. 
So the convenient Ctrl c Ctrl v should be forgotten.

**Comment by celfred** [comment] 2017-03-15 13:08
Thanks for the answer !
But the issue still remains on my side using the OpenBoard copy and paste functions in the menu at the bottom right hand corner... (OB 1.3.5 / Ubuntu 14.04)

**Comment by celfred** [comment] 2017-03-16 14:53
I keep trying to understand...
My images are still disappearing every time I copy/paste... Just to mention : I have looked at the files : when copying my image, the thumbnail is updated AND the image does appear in the SVG file (exploring the SVG with a text editor), but the generated image ID point to a non existing file. In my 'images' folder, only the first original image file is there. There's no copy :(
Maybe this helps...

**Comment by celfred** [comment] 2017-03-17 16:36
Still here...
Drag'n'drop a page with an image on a blank new document (in Document mode). Result after closing OB : go in the documents folder and you'll find 2 thumbnails : page001.thumbnail.jpg (normal) and page002.thumbnail.jpg (looking exactly the same as page001.thumbnail.jpg) but there is no page002.svg (which is normal) and looking at page001.svg shows a link towards a {9c5dc46a-480f-452d-8b63-a83af79edc4e} document in images/ folder but images/ folder is empty!
When I look at the source document folder, I can find the {9c5dc46a-480f-452d-8b63-a83af79edc4e} file in images/. Of course, if I copy this file in the destination images/ folder, the image shows up when I re-open OB.
So on my side : copying a page with a media file seems to copy the page but NOT the media files in the destination (and copy twice the thumbnail).

**Comment by freeheel3r** [comment] 2017-03-17 16:53
Hi,

Thank you for all these details! They should help narrow things down. It sounds like there's a problem in the "pasting" functions and how they handle linking to or copying objects.

We'll definitely look into it and hopefully fix it soon.

For future reference, this may be the same issue as #84

**Comment by freeheel3r** [comment] 2017-04-30 17:47
This should now be fixed (by fc81e27).
Specifically, this solves two issues:
1) When taking a partial screenshot of the desktop, then copying it
(Ctrl-C) and pasting it in a new document, the screenshot disappeared from the new document after closing and reopening OpenBoard
2) When a page of one document was copied into another (in document
mode, by dragging the page onto another document), media files
disappeared from the new page

This will be included in the next version (1.3.6), but is already available on the `dev` branch if you want to build from source.

Thanks again for helping to identify these issues! And please let me know if any related issues persist.

**Closed by freeheel3r** 2017-04-30 17:47 UTC
Labels: bug
