### ISSUE TITLE
Flatpak installation of newest version 1.7.1 doesn't start in Ubuntu 

### ISSUE THREAD

**Issue by TobiasBaeumlin** [OpenBoard-org/OpenBoard#979] opened 2024-05-22 12:50 UTC
### Describe the bug
After installing the newest flatpak version of ch.openboard.OpenBoard the program doesn't start anymore:

openboard: symbol lookup error: openboard: undefined symbol: _ZNK12QAudioSource5errorEN2Qt15Disambiguated_tE, version Qt_6

### To Reproduce
1. Install or upgrade the flatpak version of OpenBoard in Ubuntu:

flatpak update ch.openboard.OpenBoard   

or

flatpak install ch.openboard.OpenBoard 

(if not installed before.)

2. Try to run the program:
flatpak run ch.openboard.OpenBoard

#### Expected behavior
OpenBoard application starts

#### Actual behavior
Get error message:
openboard: symbol lookup error: openboard: undefined symbol: _ZNK12QAudioSource5errorEN2Qt15Disambiguated_tE, version Qt_6

### Context

  - reproducibility : `systematic` 
  - OpenBoard version :
      - bug happens with : `1.7.1`
      - bug doesn't happen with :  `1.7.0`
      - didn't check : older versions
  - OS : 
      - bug happens with :  `Linux` (Kubuntu 23.10)
      - bug doesn't happen with : `
      - didn't check : `Windows` `macOS` 
  - Installation source : flatpak

**Comment by ProbstDJakob** [comment] 2024-05-23 08:26
Same here with Fedora (39), so it is not directly linked to Ubuntu.

**Comment by bruening-bw** [comment] 2024-05-27 00:20
Same here with Debian Stable.

**Comment by kaamui** [comment] 2024-05-27 07:26
Hi @jbruechert,

Are you aware of this issue ?

Regards

**Comment by ProbstDJakob** [comment] 2024-05-27 08:50
FYI: I don't know why, but the Flatpak release states that the version 1.7.1 is about a year old (5/8/2023, 2:00:00 AM - don't know which date format this is, but probably US).

**Comment by ProbstDJakob** [comment] 2024-05-27 11:31
I can confirm, that it works. Thank you.

**Comment by letsfindaway** [comment] 2024-06-17 12:27
Closing this issue as it seems to be resolved.

**Closed by letsfindaway** 2024-06-17 12:27 UTC
Labels: bug
