### ISSUE TITLE
MultiScreen mode on Single Screen

### ISSUE THREAD

**Issue by JoseHerreraIbagos** [OpenBoard-org/OpenBoard#348] opened 2020-05-25 18:46 UTC
Great work on the app, I've seen a renewed interest due to the recent worldwide situation and I think you should take advantage on that.

U guys should consider open a Patreon (or another platform) page as a way to make specificic functionality's request a lot faster and give support to the app. If a group/university can afford it should be alowed.

My particular request and I hope is easy to implement, is that the multiscreen option works even if the the secondary display is not available, when the user try to stream a window in zoom, discord, meet or others it will find this very helpfull. Also consider changing the name of the secondary window because it can be really hard to select it in software like OBS.

As an aditional note and I know there is a request for this but, please consider add the option for key commands for brushes sizes and colors, it will increase the productivity as it can be implemented in the circular panels on Wacom tablets and other devices. 

Thank u so much, please let the people donate and support the hard work that u are doing, I know that anyone with the skills can do it but only a few are familiar with the code.

**Comment by kaamui** [comment] 2020-08-10 08:22
Hello,

First of all thank you for your support. There's already a discussion about what you suggest (#317)

For the patreon, the issue is that I don't have more time as I work on other things we develop for Geneva schools. Maybe some day we'll be able to have a second developer on the project. There are some discussions with Lausanne as OpenBoard is also widely used there.

I'll give you some update when relevant.
Regards

(I close this one as duplicate of the 317)

**Closed by kaamui** 2020-08-10 08:22 UTC
Labels: feature request, question
