### ISSUE TITLE
CTRL C/V inavaliable?

### ISSUE THREAD

**Issue by Davv73** [OpenBoard-org/OpenBoard#960] opened 2024-05-11 18:00 UTC
Hello,
The commands CRTL C/V doesn't seem to work properly. Is it a known issue and will it be corrected please?
And the format (size) of my previous UBZ, made with other versions of Open board, is not very accurate (a litle bit too big)
Thank you

**Comment by kaamui** [comment] 2024-05-13 07:50
Hi,

The issue is fixed in OpenBoard 1.7.1, that you can download here : https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.7.1/OpenBoard_Installer_1.7.1.exe

**Closed by kaamui** 2024-05-13 07:50 UTC
Labels: question
