### ISSUE TITLE
Support for Wacom Stylus pen

### ISSUE THREAD

**Issue by severus-tux** [OpenBoard-org/OpenBoard#355] opened 2020-06-07 15:55 UTC
Hi, 
  I use "One by wacom"  writing device. The stylus pen has got two buttons. It would be awesome if I could program those buttons to act like eraser and laser pointers. The buttons are programmable in general. If there is command/keyboard shortcut for picking items (like eraser etc..), I can easily map that to the buttons. 

Please let me know if there is any such techniques.

**Comment by kaamui** [comment] 2020-08-10 08:45
Hello,

The idea of making a new tab in the preferences to make shortcuts configuration possible is growing, and will probably be considered after the migration is over. 

Duplicate of #321

**Closed by kaamui** 2020-08-10 08:45 UTC
