### ISSUE TITLE
Feature request: Map tablet buttons to common actions

### ISSUE THREAD

**Issue by kzembower** [OpenBoard-org/OpenBoard#378] opened 2020-09-25 15:57 UTC
I would like to request the ability to map buttons on the tablet or pen, to various actions in the toolbars and menus. For instance, I use the Huion NEW 1060PLUS tablet, which has 12 buttons on the tablet, in addition to three buttons on the pen (the tip and two others). I would like to be able to map these buttons to specific actions, such as:

- next page/previous page
- change the tool to Pen and the color to Green
- erase all
- change the tool to the Eraser and when the button is released, go back to whatever tool was last used.
- etc.

Thank you for considering this request.

-Kevin

**Comment by SoPat712** [comment] 2020-09-27 15:51
This isn't something to do with the tablet, all OpenBoard would have to do would be to add keyboard shortcuts to the app. Please close this, as this is a duplicate of #377 , #312 #321  #93 , and a couple of others

**Comment by kzembower** [comment] 2020-09-28 16:11
Respectfully, I choose to leave this request open. I don't believe that it's a duplicate of the other tickets. Mapping tablet buttons to OpenBoard actions is different from mapping keyboard shortcuts to OpenBoard Actions. There's no guarantee that tablet buttons can be mapped to keyboard shortcuts.

I'm envisioning a system where I could select the action I want to control, say, select the Pen with the color Red, then push the button on the tablet, and, no matter what output that button-press caused, it would be mapped to the Red Pen action. 

Thanks, again, for considering this feature request, which I believe would be very popular and much used.

-Kevin

**Comment by SoPat712** [comment] 2020-09-28 16:22
I would entreat you to close this, and will advise the developers as such. Keyboard shortcuts can be mapped here 

![image](https://user-images.githubusercontent.com/30350506/94459231-10427100-0185-11eb-8066-8d3ca0f63007.png)

This can change depending on the tablet that you own.

And this is in fact a duplicate of other issues. Creating keyboard shortcuts would close 20 issues in this repo, and having another issue clogging up everything else is just a bother for the devs, making it harder for them to get their job done.

**Comment by kzembower** [comment] 2020-09-28 16:40
I believe that you're referring to the instructions and illustrations shown at https://support.huion.com/support/solutions/articles/44001909702-how-to-customize-press-keys-and-digital-pen-button-functions-for-specific-software.

Since I am using a Linux system, I have no "Huion Tablet driver" and cannot follow these instructions. Unless a similar program for Linux can be found, one that works on a per-application basis, and not a universal "pressing this button gives Control-X in every program and desktop" solution, I believe that my request remains valid.

-Kevin

**Comment by SoPat712** [comment] 2020-09-28 17:05
As a developer myself, I can say this with 100% certainty. There is no way one developer can encompass every single OS or every single problem. I don't think that the the folks at OpenBoard-Org can even think about creating a compatibility layer between your Huion tablet and OpenBoard, but by all means leave it open if you want. But I'm telling you right now, nothing will come of it.

**Closed** 2020-11-16 08:11 UTC

**Comment by kaamui** [comment] 2020-11-16 08:14
As @SoPat712 said, it's sadly impossible to me to help you on this request, as I already have a lot of work that I can't even find time to do ^^.
