### ISSUE TITLE
Compile on Debian testing

### ISSUE THREAD

**Issue by carlosuema** [OpenBoard-org/OpenBoard#142] opened 2018-05-21 16:20 UTC
Hello! If this is not the most suitable channel, I apologize in advance.
 I have successfully compiled a version of this program in debian stretch successfully. For this reason, I decided to build a source package as required by the debian standard. However, I do not understand programming itself, but only about the packaging process. That's why I'm contacting you for help solving this problem that comes with compiling the program in debian testing:

make [1]: Entering directory '/ root / openboard / OpenBoard'
g ++ -c -m64 -pipe -std = c ++ 11 -fopenmp -O2 -w -D_REENTRANT -fPIC -DQUAZIP_STATIC -DNO_THIRD_PARTY_WARNINGS -DUBVERSION = "\" 1.4.0. "\" -DUBVERSION_RC = 1,4,0,240, 0 -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB -Isrc -I ../ OpenBoard-ThirdParty / zLib / 1.2.8 / include - I / OpenPlus / xpdf / xpdf-3.04 -I ../ OpenBoard-ThirdParty / xpdf / xpdf-3.04 / goo -I ../ OpenBoard-ThirdParty / xpdf / xpdf-3.04 / splash -Isrc / web / browser -Isrc / pdf-merger -I ../ OpenBoard-ThirdParty / quazip -I ../ OpenBoard-ThirdParty / zlib / 1.2.8 / include -I ../ OpenBoard-ThirdParty / quazip / quazip-0.7.1 - I ../ OpenBoard-ThirdParty / qt / singleapplication -I ../ OpenBoard-ThirdParty / qt / singleapplication -I ../ OpenBoard-ThirdParty / qt / lockedfile -isystem / usr / include / x86_64-linux-gnu / qt5 - isystem / usr / include / x86_64-linux-gnu / qt5 / QtWebKitWidgets -isystem / usr / include / x86_64-linux-gnu / qt5 / QtWebKit -isystem / usr / include / x86_64-linux-gnu / qt5 / QtSvg -isystem / usr / include / x86_64-linux-gnu / qt5 / QtUiTools -isystem / usr / include / x86_64-linux-gnu / qt5 / QtMultimediaWidgets -isystem / usr / include / x86_64-linux-gnu / qt5 / QtPrintSupport -isystem / usr / include / x86_64-linux-gnu / qt5 / QtWidgets -isystem / usr / include / x86_64-linux-gnu / qt5 / QtMultimedia -isystem / usr / include / x86_64-linux-gnu / qt5 / QtGui -isystem / usr / include / x86_64-linux-gnu / qt5 / QtXmlPatterns -isystem / usr / include / x86_64-linux-gnu / qt5 / QtNetwork -isystem / usr / include / x86_64-linux-gnu / qt5 / QtXml -isystem / usr / include / x86_64-linux-gnu / qt5 / QtScript -isystem / usr / include / x86_64 -linux-gnu / qt5 / QtCore -Ibuild / linux / release / moc -isystem / usr / include / libdrm -Ibuild / linux / release / ui -I / usr / lib / x86_64-linux-gnu / qt5 / mkspecs / linux -g ++ - 64 -o build / linux / release / objects / UBFFmpegVideoEncoder or src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: In member function 'bool UBFFmpegVideoEncoder :: init ()':
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: 415: 23: error: 'swr_alloc' was not declared in this scope
         mSwrContext = swr_alloc ();
                       ^ ~~~~~~~~
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: 415: 23: note: suggested alternative: 'realloc'
         mSwrContext = swr_alloc ();
                       ^ ~~~~~~~~
                       realloc
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: 430: 15: error: 'swr_init' was not declared in this scope
         ret = swr_init (mSwrContext);
               ^ ~~~~~~~
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: 430: 15: note: suggested alternative: 'init'
         ret = swr_init (mSwrContext);
               ^ ~~~~~~~
               init
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: In member function 'void UBFFmpegVideoEncoder :: processAudio (QByteArray &)':
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: 550: 27: error: 'swr_get_out_samples' was not declared in this scope
     int outSamplesCount = swr_get_out_samples (mSwrContext, inSamplesCount);
                           ^ ~~~~~~~~~~~~~~~~~~
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: 550: 27: note: suggested alternative: 'avresample_get_out_samples'
     int outSamplesCount = swr_get_out_samples (mSwrContext, inSamplesCount);
                           ^ ~~~~~~~~~~~~~~~~~~
                           avresample_get_out_samples
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: 565: 11: error: 'swr_convert' was not declared in this scope
     ret = swr_convert (mSwrContext,
           ^ ~~~~~~~~~~
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: 565: 11: note: suggested alternative: 'sws_convVec'
     ret = swr_convert (mSwrContext,
           ^ ~~~~~~~~~~
           sws_convVec
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: In member function 'void UBFFmpegVideoEncoder :: finishEncoding ()':
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: 650: 9: error: 'swr_free' was not declared in this scope
         swr_free (& mSwrContext);
         ^ ~~~~~~~
src / podcast / ffmpeg / UBFFmpegVideoEncoder.cpp: 650: 9: note: suggested alternative: 'av_free'
         swr_free (& mSwrContext);
         ^ ~~~~~~~
         av_free
Makefile.Release: 6021: recipe for target 'build / linux / release / objects / UBFFmpegVideoEncoder.o' failed
make [1]: *** [build / linux / release / objects / UBFFmpegVideoEncoder.o] Error 1
make [1]: Leaving directory '/ root / openboard / OpenBoard'
Makefile: 40: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by Arvil** [comment] 2018-05-24 07:14
In UBFFmpegVideoEncoder.cpp add at the beginning (among includes):

'''
extern "C" {
    #include<libswresample/swresample.h>
} 
'''

**Comment by juanjosepablos** [comment] 2018-10-24 20:13
Looks like this bug is duplicate to  #170

**Comment by juanjosepablos** [comment] 2018-10-30 09:39
well, if that makes you happy then #170 is duplicate of this one. But the other bug has more information and code that it is used to compile a Debian package. It is important to focus in one bug. the other bugs are just noise.

**Comment by kaamui** [comment] 2019-01-09 15:09
Thank you for the feedback. 

The discussion can continue, if needed, on #170, because it is more active.

**Closed by kaamui** 2019-01-09 15:09 UTC
